import { Category, Transaction } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { name: 'Étkezés', icon: 'Utensils', color: '#f43f5e', budget: 150000, type: 'expense' },
  { name: 'Vásárlás', icon: 'ShoppingBag', color: '#eab308', budget: 80000, type: 'expense' },
  { name: 'Lakhatás', icon: 'Home', color: '#3b82f6', budget: 250000, type: 'expense' },
  { name: 'Közlekedés', icon: 'Car', color: '#a855f7', budget: 60000, type: 'expense' },
  { name: 'Szórakozás', icon: 'Tv', color: '#6366f1', budget: 50000, type: 'expense' },
  { name: 'Rezsi', icon: 'Zap', color: '#f97316', budget: 70000, type: 'expense' },
  { name: 'Egészségügy', icon: 'HeartPulse', color: '#14b8a6', budget: 40000, type: 'expense' },
  { name: 'Fizetés', icon: 'Briefcase', color: '#10b981', type: 'income' },
  { name: 'Befektetés', icon: 'TrendingUp', color: '#06b6d4', type: 'income' },
  { name: 'Egyéb', icon: 'DollarSign', color: '#6b7280', budget: 30000, type: 'both' },
];

export const DEFAULT_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    description: 'Havi fizetés',
    amount: 650000,
    type: 'income',
    category: 'Fizetés',
    date: '2026-07-01',
    notes: 'Rendszeres havi bér',
  },
  {
    id: '2',
    description: 'Lakbér',
    amount: 220000,
    type: 'expense',
    category: 'Lakhatás',
    date: '2026-07-02',
    notes: 'Esedékes 1-jén',
  },
  {
    id: '3',
    description: 'Heti nagybevásárlás',
    amount: 42500,
    type: 'expense',
    category: 'Étkezés',
    date: '2026-07-05',
    notes: 'Tesco',
  },
  {
    id: '4',
    description: 'Villanyszámla',
    amount: 24800,
    type: 'expense',
    category: 'Rezsi',
    date: '2026-07-08',
  },
  {
    id: '5',
    description: 'Szabadúszó munka',
    amount: 95000,
    type: 'income',
    category: 'Befektetés',
    date: '2026-07-10',
    notes: 'UI design',
  },
  {
    id: '6',
    description: 'Mozi jegyek',
    amount: 8600,
    type: 'expense',
    category: 'Szórakozás',
    date: '2026-07-12',
    notes: '2 jegy + popcorn',
  },
  {
    id: '7',
    description: 'Új cipő',
    amount: 34900,
    type: 'expense',
    category: 'Vásárlás',
    date: '2026-07-13',
  },
  {
    id: '8',
    description: 'BKK bérlet',
    amount: 9500,
    type: 'expense',
    category: 'Közlekedés',
    date: '2026-07-14',
  },
  {
    id: '9',
    description: 'Vacsora a barátokkal',
    amount: 18700,
    type: 'expense',
    category: 'Étkezés',
    date: '2026-07-15',
  }
];
