import { Category, Transaction } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { name: 'Food & Dining', icon: 'Utensils', color: '#f43f5e', budget: 150000 },
  { name: 'Shopping', icon: 'ShoppingBag', color: '#eab308', budget: 80000 },
  { name: 'Housing & Rent', icon: 'Home', color: '#3b82f6', budget: 250000 },
  { name: 'Transportation', icon: 'Car', color: '#a855f7', budget: 60000 },
  { name: 'Entertainment', icon: 'Tv', color: '#6366f1', budget: 50000 },
  { name: 'Utilities', icon: 'Zap', color: '#f97316', budget: 70000 },
  { name: 'Healthcare', icon: 'HeartPulse', color: '#14b8a6', budget: 40000 },
  { name: 'Salary', icon: 'Briefcase', color: '#10b981' },
  { name: 'Investments', icon: 'TrendingUp', color: '#06b6d4' },
  { name: 'Others', icon: 'DollarSign', color: '#6b7280', budget: 30000 },
];

export const DEFAULT_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    description: 'Monthly Salary',
    amount: 650000,
    type: 'income',
    category: 'Salary',
    date: '2026-07-01',
    notes: 'Regular monthly payout',
  },
  {
    id: '2',
    description: 'Apartment Rent',
    amount: 220000,
    type: 'expense',
    category: 'Housing & Rent',
    date: '2026-07-02',
    notes: 'Due on 1st, paid on 2nd',
  },
  {
    id: '3',
    description: 'Weekly Grocery Shopping',
    amount: 42500,
    type: 'expense',
    category: 'Food & Dining',
    date: '2026-07-05',
    notes: 'Tesco supermarket',
  },
  {
    id: '4',
    description: 'Electricity Bill',
    amount: 24800,
    type: 'expense',
    category: 'Utilities',
    date: '2026-07-08',
  },
  {
    id: '5',
    description: 'Freelance Design Gig',
    amount: 95000,
    type: 'income',
    category: 'Investments',
    date: '2026-07-10',
    notes: 'UI design work for client',
  },
  {
    id: '6',
    description: 'Cinema Tickets',
    amount: 8600,
    type: 'expense',
    category: 'Entertainment',
    date: '2026-07-12',
    notes: 'Two tickets + popcorn',
  },
  {
    id: '7',
    description: 'New Sneakers',
    amount: 34900,
    type: 'expense',
    category: 'Shopping',
    date: '2026-07-13',
  },
  {
    id: '8',
    description: 'Public Transport Pass',
    amount: 9500,
    type: 'expense',
    category: 'Transportation',
    date: '2026-07-14',
  },
  {
    id: '9',
    description: 'Dinner with friends',
    amount: 18700,
    type: 'expense',
    category: 'Food & Dining',
    date: '2026-07-15',
  }
];
